### ISSUE TITLE
Inclusion of other SMILES dialects?

### ISSUE THREAD

**Issue by smoretti** [vfscalfani/IUPAC_SMILES_plus#5]
What about 
- https://github.com/nextmovesoftware/deepsmiles
- http://www.axeleratio.com/csm/proj/language.htm

**Comment by UnixJunkie** [comment]
Also, why not just contribute to the open smiles specification?

**Comment by smoretti** [comment]
I am not involved in any of those projects, just heard about them.
I am just a SMILES user, and not a chemist.
How could I contribute?

**Comment by vfscalfani** [comment]
Hello, 

Many thanks for these comments and questions. 

**1.	Will we include other SMILES dialects such as DeepSMILES and CurlySmiles into the specification?**

Maybe. I think our first goal is to define a core “baseline” IUPAC SMILES+. Extensions that are already well-supported will likely be included such as quadruple bonds. However, if we add too many extensions and variations, it will be harder for toolkits to officially support. We should absolutely document these, perhaps in an appendix.

**2.	Why not just contribute to OpenSMILES?** 

Great question. We feel that IUPAC SMILES+ is a natural progression of OpenSMILES (evident also as we are starting from OpenSMILES). Maintaining a SMILES specification under IUPAC gives us some formal organizational support to develop a long-term maintenance plan and sustainability model. In addition, since InChI is under IUPAC, bringing SMILES into IUPAC should allow us to collaborate closely. 

**3.	How can you contribute?** 

Here are a couple tasks we would like to tackle over the next few months. Any contributions welcome!

1.	We would like to modify this document (https://github.com/IUPAC/IUPAC_SMILES_plus/blob/master/toolkit_doc_compare/toolkit_SMILES_docs_comparison.asciidoc) and create a table of all known SMILES extension notation, this way future extensions can avoid symbol overlap. 

2.	If you are comfortable with code, you could add in new scripts that are useful for calculating InChIs from a list of SMILES (e.g., using CDK, Indigo). See here: https://github.com/IUPAC/IUPAC_SMILES_plus/tree/master/validation_data/01_scripts

We are using these scripts to identify edge cases where there are differences across toolkits when reading SMILES. The edge cases will help inform the specification writing. 

Vin
